### ISSUE TITLE
Add MIT LICENSE

### ISSUE THREAD

**Issue by DipanshKhandelwal** [DipanshKhandelwal/Learning-German#10]

**Comment by trevlewis** [comment]
I can do this.

**Comment by DipanshKhandelwal** [comment]
Sure @trevlewis :+1:

**Comment by DipanshKhandelwal** [comment]
Fixed by #11

**Comment by trevlewis** [comment]
@DipanshKhandelwal that wasn't my commit....

**Comment by DipanshKhandelwal** [comment]
@trevlewis I am really sorry I did not check it :sweat_smile: . Please take up something new now, ill take care of it next time.
